#!/bin/sh

# todo:
# 1. make full installation work off a relative path
# 2. make configure scripts work off a relative path
# 3. make it work for windows + linux
# 4. make luajit not use /usr/share etc for lookups

export DIST=~/personal-installed/dist-rocket

rm -rf $DIST

cd LuaJit-2.0.2
make clean
make
make install
rm -f $DIST/lib/libluajit*
rm -rf $DIST/share/luajit*
rm -rf $DIST/include

cd ../cosmo-13.01.30
./configure $DIST/bin/luajit
make clean
make
make install

cd ../lpeg-0.10.2
make clean
make
cp lpeg.so $DIST/lib/lua/5.1
cp re.lua $DIST/share/lua/5.1

cd ../leg-0.1.2
make clean
make
make install

cd ../luma-0.2
./configure $DIST/bin/luajit
make clean
make
make install
mv $DIST/bin/luma $DIST/bin/rocket

cd ../rings-1.3.0
./configure
make clean
make
make install

#cd ../penlight-1.3.1
#cp -r lua/pl $DIST/share/lua/5.1

cd ../microlight-1.1.1
cp ml.lua $DIST/share/lua/5.1

